# Generated by Django 3.1.5 on 2021-01-31 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookmarks.category'),
        ),
    ]
