# Generated by Django 3.1.5 on 2021-02-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_auto_20210210_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
